language: node_js
node__js:
  - "12"
cache:
  npm: false
  directories:
    - node_modules
    - client/ node_modules
    - server/ node_modules
script: npm i && cd client && npm i && npm run eslint && npm run testCi && cd ../server && npm i && npm test && cd ..
