language: node_js
node__js:
  - "12"
cache:
  npm: false
  directories:
    - client/ node_modules
    - server/ node_modules
script: cd client && npm install && npm run testCi && cd ../server && npm install && npm test
